import { SessionProvider } from '@/components/SessionProvider'
import SideBar from '../components/SideBar'
import { getServerSession } from 'next-auth'
import '@/styles/globals.css'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Login from '@/components/Login'
import ClientProvider from '@/components/ClientProvider'
import Navbar from '@/components/NavBar'
import { Disclosure } from "@headlessui/react"

export const metadata = {
  title: 'Straya GPT',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className='h-screen flex justify-start'>
              <div className='md:w-60 lg:96 flex shrink-0'>
                <SideBar />
              </div>
              <ClientProvider />
              <div className="flex-1 flex-shrink">{children}</div>
            </div>
          )}

        </SessionProvider>
      </body>
    </html >
  )
}
